import Head from 'next/head'
import { parse } from 'node-html-parser';



export default function Home({ article, products, content }) {
  console.log(article)
  console.log(products)  
  console.log(content)
  return (
    <div>
      <Head>
        <title>Next Amazon</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

      <h1>{ article.title.rendered}</h1>
      <div>
      
      </div>
      
    </div>
  )
}


// OTHER FUNCTIONS
const options = {
  'method': 'GET'
}

const getArticle = async (id) => {
  const articleData = await fetch(`https://sub.revoou.com/wp-json/wp/v2/articles/${id}`, options)
  return (
    await articleData.json()
  )
}

const getProducts = async (productIds) => {  
  let productData = []
  
  for(const productId of productIds){
    const data = await (await fetch(`https://sub.revoou.com/wp-json/wp/v2/products/${productId}`, options)).json()
    productData.push(data)
  }
  return  (
    productData
  ) 
}



// This gets called on every request
export async function getServerSideProps() {
  
  // Fetch data from external API
  
  const article =  await getArticle(32)
  // const productIds = await 
  const products = await getProducts(article.acf.table_products)
  const content = {}
  

  
  

  // Pass data to the page via props
  return { props: { article, products, content } }
}


